name: Pylint Odoo

on:
  push:
    branches:
      - main
      #- "18.0"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      # setup python 3.12
      - name: Set Up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Listando repositorio
        run: git ls-files '*py'
      
      - name: Analizando el código con flake8
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pylint
          flake8 --ignore=F401 $(git ls-files '*py')
